services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astronautics-nextjs
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - uploads_data:/app/public/uploads
      - logs_data:/app/logs
    networks:
      - astronautics-network

  nginx:
    image: nginx:alpine
    container_name: astronautics-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - uploads_data:/usr/share/nginx/html/uploads
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nextjs
    networks:
      - astronautics-network

volumes:
  uploads_data:
    driver: local
  logs_data:
    driver: local

networks:
  astronautics-network:
    driver: bridge
