name: Deploy to Server
permissions:
  contents: read

on:
    push:
        branches: ["main"]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Clone the repo
              uses: actions/checkout@v6

            - name: Install npm
              uses: actions/setup-node@v6
              with:
                node-version: '25'
                cache: 'npm'

            - name: Sync project to deployment directory
              run: |
                  rsync -av --delete --exclude=".env.local" --exclude="node_modules" --exclude=".next" ./ ~/astronauticsclub-iiith.github.io/

            - name: Install and build the project
              run: |
                  cd ~/astronauticsclub-iiith.github.io
                  npm ci
                  npm run build

            - name: Restart server
              run: |
                  pm2 restart astronautics || pm2 start ecosystem.config.cjs
                  pm2 save
